/*
 * gGUIEvents.h
 *
 *  Created on: Feb 4, 2022
 *      Author: noyan
 */

#ifndef UI_GGUIEVENTS_H_
#define UI_GGUIEVENTS_H_

#define G_GUIEVENT_NONE 0
#define G_GUIEVENT_BUTTONPRESSED 1
#define G_GUIEVENT_BUTTONRELEASED 2
#define G_GUIEVENT_TEXTBOXENTRY 3
#define G_GUIEVENT_CHECKBOXTICKED 4
#define G_GUIEVENT_CHECKBOXUNTICKED 5
#define G_GUIEVENT_LISTBOXSELECTED 6
#define G_GUIEVENT_SWITCHBUTTON_ON 7
#define G_GUIEVENT_SWITCHBUTTON_OFF 8
#define G_GUIEVENT_COLORBOX_CHANGED 9
#define G_GUIEVENT_TREELISTSELECTED 10
#define G_GUIEVENT_MENUBARSELECTED 11
#define G_GUIEVENT_TREELISTOPENEDONDROPDOWNLIST 12
#define G_GUIEVENT_MOUSEPRESSEDONTREELIST 13
#define G_GUIEVENT_TREELISTEXPANDED 14
#define G_GUIEVENT_COLORSELECTED 15
#define G_GUIEVENT_PANEACTIVE 16

//changed




#endif /* UI_GGUIEVENTS_H_ */
