# gen_vk_shaders.cmake
#
# Compiles the engine's shader sources in this directory to SPIR-V and writes them
# as uint32 arrays into engine/core/gVKShaders.h. That header is committed so the
# engine builds without a shader compiler present; this only has to run when a
# shader changes.
#
# engine/CMakeLists.txt runs it automatically whenever one of the sources is
# newer than the header. To run it by hand:
#
#   cmake -DGLSLC=<path to glslc> -DSHADER_DIR=<this directory> \
#         -DOUT=<path to engine/core/gVKShaders.h> -P gen_vk_shaders.cmake
#
# It is written in CMake rather than a shell script so that Windows regenerates
# the header the same way macOS and Linux do - a shell script left Windows
# silently shipping a stale gVKShaders.h.

if(NOT DEFINED GLSLC OR NOT DEFINED SHADER_DIR OR NOT DEFINED OUT)
	message(FATAL_ERROR "gen_vk_shaders.cmake needs -DGLSLC, -DSHADER_DIR and -DOUT")
endif()

# Array name, source file relative to this directory, shader stage, and one extra
# macro to define (- for none). Add a row here when a shader joins the path;
# gVKPipeline.cpp reads the arrays by these names.
#
# Every source now lives beside the OpenGL shaders and carries its Vulkan
# declarations in an #if VULKAN block; this directory holds only the generator.
# color_vert/color_frag appear twice because OpenGL draws both its 2D primitives
# and its 3D meshes with one program while Vulkan needs a pipeline for each, so
# the file is compiled once as VULKAN2D and once as VULKAN3D.
set(GVK_SHADERS
	gvkspv_color2d_vert   color_vert.glsl     vertex   VULKAN2D
	gvkspv_color2d_frag   color_frag.glsl     fragment VULKAN2D
	gvkspv_image2d_vert   image_vert.glsl     vertex   -
	gvkspv_image2d_frag   image_frag.glsl     fragment -
	gvkspv_mesh3d_vert    color_vert.glsl     vertex   VULKAN3D
	gvkspv_mesh3d_frag    color_frag.glsl     fragment VULKAN3D
	gvkspv_mesh3dpbr_vert pbr_vert.glsl       vertex   -
	gvkspv_mesh3dpbr_frag pbr_frag.glsl       fragment -
	gvkspv_shadow3d_vert  shadowmap_vert.glsl vertex   -
	gvkspv_shadow3d_frag  shadowmap_frag.glsl fragment -
	gvkspv_skybox3d_vert  skybox_vert.glsl    vertex   -
	gvkspv_skybox3d_frag  skybox_frag.glsl    fragment -
	gvkspv_fbo_vert       fbo_vert.glsl       vertex   -
	gvkspv_fbo_frag       fbo_frag.glsl       fragment -
	gvkspv_magnifier_frag  magnifier_frag.glsl  fragment -)

set(GVK_HEADER "/*
 * gVKShaders.h
 *
 * SPIR-V for the engine's Vulkan shaders, generated by gen_vk_shaders.cmake
 * from the shader sources in engine/graphics/shaders, which the OpenGL backend
 * compiles the other half of.
 * Do not edit by hand: change the .glsl source and rebuild.
 */

#pragma once

#include <cstdint>

")

# Whether the committed SPIR-V still corresponds to these sources is a question
# about the sources, not about the clock and not about the compiler. Timestamps
# answer it wrongly in both directions: a fresh clone or a branch switch sets
# every file's modification time at once and in no useful order, so the rule
# fires with nothing changed - and then whichever glslc the developer happens to
# have rewrites the header, because two versions of the optimiser do not emit the
# same words for the same source. The result is a committed binary that changes
# from machine to machine and conflicts on every merge.
#
# So the header records a hash of the sources it was generated from, and the
# generator stops here when that hash still matches. Editing a shader changes it
# and the SPIR-V is regenerated; upgrading a compiler does not, and the committed
# bytes stay put. Pass -DFORCE=ON to regenerate anyway, which is what a
# deliberate toolchain upgrade wants.
set(GVK_HASH_INPUT "")
list(LENGTH GVK_SHADERS GVK_HASH_COUNT)
math(EXPR GVK_HASH_LAST "${GVK_HASH_COUNT} - 1")
foreach(i RANGE 0 ${GVK_HASH_LAST} 4)
	math(EXPR j "${i} + 1")
	list(GET GVK_SHADERS ${j} file)
	file(READ "${SHADER_DIR}/${file}" GVK_ONE_SOURCE)
	string(APPEND GVK_HASH_INPUT "${file}\n${GVK_ONE_SOURCE}")
endforeach()
# The generator itself is part of the input: change how the header is written and
# the header has to be rewritten.
file(READ "${CMAKE_CURRENT_LIST_FILE}" GVK_GENERATOR_SOURCE)
string(APPEND GVK_HASH_INPUT "${GVK_GENERATOR_SOURCE}")
string(SHA256 GVK_HASH "${GVK_HASH_INPUT}")
set(GVK_HASH_LINE "// source-sha256: ${GVK_HASH}")

if(NOT FORCE AND EXISTS "${OUT}")
	file(STRINGS "${OUT}" GVK_RECORDED_HASH REGEX "^// source-sha256: ")
	if(GVK_RECORDED_HASH STREQUAL GVK_HASH_LINE)
		message(STATUS "Vulkan shader sources unchanged; keeping the committed SPIR-V in ${OUT}")
		return()
	endif()
endif()

list(LENGTH GVK_SHADERS GVK_SHADER_COUNT)
math(EXPR GVK_LAST "${GVK_SHADER_COUNT} - 1")
foreach(i RANGE 0 ${GVK_LAST} 4)
	list(GET GVK_SHADERS ${i} name)
	math(EXPR j "${i} + 1")
	list(GET GVK_SHADERS ${j} file)
	# The stage is named rather than inferred: a shader shared with the OpenGL
	# backend is called _vert.glsl or _frag.glsl, and glslc reads no stage out of
	# a .glsl extension.
	math(EXPR k "${i} + 2")
	list(GET GVK_SHADERS ${k} stage)
	math(EXPR l "${i} + 3")
	list(GET GVK_SHADERS ${l} extradefine)
	set(GVK_DEFINE_ARG "")
	if(NOT extradefine STREQUAL "-")
		set(GVK_DEFINE_ARG "-D${extradefine}=1")
	endif()

	# -mfmt=c emits the SPIR-V as a braced C initialiser; -o - sends it to stdout,
	# so no temporary file is needed. The flags match what the engine's runtime
	# compiler uses, so both paths produce the same code.
	#
	# The shader declares its version in each dialect block, which is where it
	# belongs and what gShader reads on the OpenGL side. glslc cannot be given it
	# that way - GLSL requires #version to be the first thing in a shader, and
	# glslang enforces that before any #if is resolved - so the version is lifted
	# out of the Vulkan block and handed over as -std, and the #version lines are
	# removed from what glslc is fed. The file stays the one place the version is
	# stated; this only carries it across a syntax the compiler will not take.
	#
	# VULKAN needs no -D: glslang predefines it whenever the target is Vulkan,
	# which is what the shared sources branch on.
	file(STRINGS "${SHADER_DIR}/${file}" GVK_SOURCE_LINES)
	set(GVK_STD "")
	set(GVK_IN_VULKAN_BLOCK OFF)
	set(GVK_STRIPPED "")
	foreach(sourceline IN LISTS GVK_SOURCE_LINES)
		if(sourceline MATCHES "^#if[ \t]+VULKAN")
			set(GVK_IN_VULKAN_BLOCK ON)
		elseif(sourceline MATCHES "^#(if|else|endif)")
			set(GVK_IN_VULKAN_BLOCK OFF)
		endif()
		if(sourceline MATCHES "^#version[ \t]+([0-9]+)[ \t]*([a-z]*)")
			if(GVK_IN_VULKAN_BLOCK AND GVK_STD STREQUAL "")
				set(GVK_PROFILE "${CMAKE_MATCH_2}")
				if(GVK_PROFILE STREQUAL "")
					set(GVK_PROFILE "core")
				endif()
				set(GVK_STD "${CMAKE_MATCH_1}${GVK_PROFILE}")
			endif()
			# Dropped whichever block it came from: only one version can reach the
			# compiler, and it arrives as -std.
			string(APPEND GVK_STRIPPED "\n")
		else()
			string(APPEND GVK_STRIPPED "${sourceline}\n")
		endif()
	endforeach()
	if(GVK_STD STREQUAL "")
		message(FATAL_ERROR "${file} declares no #version inside an #if VULKAN block")
	endif()
	# Written beside the header rather than next to the sources, so a source tree
	# stays clean and a stale copy cannot be mistaken for a shader.
	get_filename_component(GVK_OUT_DIR "${OUT}" DIRECTORY)
	set(GVK_TEMP "${GVK_OUT_DIR}/.gvk_${name}.glsl")
	file(WRITE "${GVK_TEMP}" "${GVK_STRIPPED}")
		# gMagnifier sets its uniform-block members by name through gShader.
	# Keep OpMemberName reflection data in its embedded SPIR-V.
	set(GVK_OPTIMIZATION "-O")
	if(name STREQUAL "gvkspv_magnifier_frag")
		set(GVK_OPTIMIZATION "")
	endif()

	execute_process(
		COMMAND "${GLSLC}" --target-env=vulkan1.2 ${GVK_OPTIMIZATION} -std=${GVK_STD} -fshader-stage=${stage}
				${GVK_DEFINE_ARG} "${GVK_TEMP}" -mfmt=c -o -
		OUTPUT_VARIABLE spirv
		ERROR_VARIABLE glslcerror
		RESULT_VARIABLE glslcresult)
	file(REMOVE "${GVK_TEMP}")
	if(NOT glslcresult EQUAL 0)
		message(FATAL_ERROR "glslc failed on ${file}:\n${glslcerror}")
	endif()

	string(APPEND GVK_HEADER "static const uint32_t ${name}[] =\n${spirv};\n\n")
endforeach()

string(APPEND GVK_HEADER "${GVK_HASH_LINE}\n")

# Only touch the header when the bytes actually change, so an unrelated rebuild
# does not keep restamping a committed file.
set(GVK_EXISTING "")
if(EXISTS "${OUT}")
	file(READ "${OUT}" GVK_EXISTING)
endif()
if(NOT GVK_EXISTING STREQUAL GVK_HEADER)
	file(WRITE "${OUT}" "${GVK_HEADER}")
	message(STATUS "Wrote ${OUT}")
else()
	message(STATUS "${OUT} is already up to date")
endif()
